;; Calculate row n, column i
(define (pascal n i)
    (cond ((> i n) 0)
          ((<= i 0) 0)
          ((= i 1) 1)
          ((= n 1) 1)
          (else (+ (pascal (- n 1) i)
                   (pascal (- n 1) (- i 1))))))

(pascal 1 1)
(pascal 2 1)
(pascal 2 2)
(pascal 3 1)
(pascal 3 2)
(pascal 3 3)
(pascal 4 1)
(pascal 4 2)
(pascal 4 3)
(pascal 4 4)
(pascal 5 1)
(pascal 5 2)
(pascal 5 3)
(pascal 5 4)
(pascal 5 5)
